### ISSUE TITLE
Update current code with consistent photometry across WSA/VSA (small changes)

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#126]
Skeleton for script to do this.

Modified columns to track calibration changes.

Added in initial selection of data

**Comment by tms-epcc** [comment]
11/JUL/24
- part of the calibration
- will not include in the first release
- will investigate the literature for values to use in  the 1st release

**Comment by tms-epcc** [comment]
22/OCT/24
done
