### ISSUE TITLE
Run ProgrammeBuilder.

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#131]
There may be issues with different filter setups used in VVV and VVVX

Inserted ProgrammeFrame entries for VVV frames into VVVX

Fixed initial issue with setting up positional groups in ProgrammeBuilder. Need to sort out issue with determining OB setup finding best/forcing it to use one. 

Added option to not use contemporary colours.

**Comment by tms-epcc** [comment]
15/DEC/23
- now looking at how to do this.

**Comment by tms-epcc** [comment]
08/MAY/24
- added option to run without setting up the contemporary colours.  Now testing this. Working through the resulting issues.
- After this can do the stacking
- Want to add a further option to update schema later but keep positions.  Testing on a test db
- Set up QC - will speak to @MikeeRead about this

**Comment by tms-epcc** [comment]
05/JUN/24
- ran option to run without setting up the contemporary colours.
- waiting for @MikeeRead to complete QC 
- still to do further option to update schema later - will do once stacking is running

**Comment by tms-epcc** [comment]
14/AUG/24
@wfastrononomer reported this is done
