### ISSUE TITLE
Run QC when all data ingested.

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#138]
All VHS data are now in.

I've email Richard McMahon and asked yet again for any QC

pinged RGM 2023-05-05

Got a response from RGM but not that useful. Giving him a few weeks more 2023-07-14

Nothing useful from RGM so proceeding with similar QC to previous.

**Comment by tms-epcc** [comment]
18/DEC/23
@wfastrononomer and @esutorius confirmed this is closed
