### ISSUE TITLE
Set up VVVXDR1 release database

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#170]
Copy detection tables to release data base

**Comment by dr-bob** [comment]
As far as I'm aware, that's all the relevant data copied to the vvvDetectionPawPrints and vvvDetectionTiles tables in the VVVXDR1 database. However, the process took quite a long time and had to be stopped and started a few times, so it'll be worth having a second pair or eyes check the data to makes sure everything that's supposed to be in there really is there before we close this issue.
