### ISSUE TITLE
Complete general mosaicing pipeline

### ISSUE THREAD

**Issue by RoyWilliams** [wfau/ScienceArchives#39]
Modify Aurelio's code to fit in the pipeline. This is linked to card https://github.com/wfau/ScienceArchives/issues/1

Merged most of Aurelio's changes in. Added more infrastructure and testing. https://forge.roe.ac.uk/trac/VDFSarchive/changeset/12847

Aurelio doing some testing.

**Comment by wfastrononomer** [comment]
Aurelio and I are happy with the algorithm. We now need to do thorough testing.
