### ISSUE TITLE
Found possible issue with zeropoints. Need to investigate.

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#394]
Once I sorted out the data wrangling with DR5, I find that cu8 deprecates all the NB118 data, and ~75% of the J, H, Ks  but none of the Y band. This means the difference in zero point between the deep and epochs is >0.2 mag. I thought that I might have added in the VegaToAB correction wrongly, but don't think this is the issue. I will look into this more. 

Starting to calculate average offsets. Think some data is missing in the cu8 checks. Investigating.

Mostly done - it was incorrect matching to filter and misclassification.

**Comment by tms-epcc** [comment]
08/SEP/23
- @wfastrononomer started again on this
- issue with log file having only deprecated information
- perhaps look at OSA fixes 
- as yet no real conclusions

**Comment by tms-epcc** [comment]
22/SEP/23
- looking back through log files
- no insight as yet on resolving

**Comment by tms-epcc** [comment]
05/OCT/23
@wfastrononomer reported 
- looking back through log files did not help identify a solution
- trying to identify another to resolve this

**Comment by tms-epcc** [comment]
02/NOV/23
@wfastrononomer reported
- identified some bugs
- output more consistent but requires more checking.

**Comment by tms-epcc** [comment]
17/NOV/23
- a few more checks to do 
- will focus on this release 
- once done will go straight to DR6

**Comment by tms-epcc** [comment]
15/DEC/23
- created new clean test DB in order to verify the fix works 
- now running the tests

**Comment by tms-epcc** [comment]
01/FEB/24 
@wfastrononomer confirmed this is now fixed but the code is awaiting final commit,

**Comment by wfastrononomer** [comment]
Now only about 1000 images are deprecated. Do I need to do further checks or is this about the expected numbers. 
Check statistics of deltaZP. Look at a few images. Look at log files - is this an issue with number of calibration.
