### ISSUE TITLE
Check existence of all data vs WSA db entries

### ISSUE THREAD

**Issue by esutorius** [wfau/ScienceArchives#403]

**Comment by tms-epcc** [comment]
11/AUG/23
@esutorius reported
- Currently hunting for data that we do not have.  Looking for this at Cambridge but their machines are down.  Will continue once these are back up.

**Comment by tms-epcc** [comment]
25/AUG/23
 - retrieved the missing files
 - still files on disk (different versions) - these have now been ingested
 - waiting for Mike Irwin to reply
 - had problems with offline disks in Cambridge

**Comment by tms-epcc** [comment]
08/SEP/23
- still ingesting previously missing files 
- code is ignoring such files without giving any error message

**Comment by tms-epcc** [comment]
22/SEP/23
- C2 switch off affected this and so have to start again

**Comment by tms-epcc** [comment]
02/OCT/23
@esutorius reported via email 
- "The metadata ingests are now as complete as they could be. The next step will be the checking for missing catalogues and ingest them."
