### ISSUE TITLE
Modify metadata tableset (XML) document generator

### ISSUE THREAD

**Issue by stvoutsin** [wfau/ScienceArchives#416]
- Ouput short as short instead of unsignedByte
- Remove arraysize for types that are not arrays
- .. Document & Experiment with other fields that may need to be modified

**Comment by tms-epcc** [comment]
01/AUG/23
- @stvoutsin discussing possible ways forward with @esutorius

**Comment by tms-epcc** [comment]
31/AUG/23 
- discussed with @esutorius 
- not sure of which approach to take yet 
- firstly will make sure do not create errors then secondly will check output fields are the correct types
- if changes to generator are to made then Eckhard will need the requirements on fields to be mapped.  Stelios will create them if needed.

**Comment by tms-epcc** [comment]
18/SEP/23
- need to understand whether to use existing metadata tables or modify the generator

**Comment by tms-epcc** [comment]
04/OCT/23
- have created search/replace
- will now test this 
- if not successful, will need to speak to Eckhard

**Comment by tms-epcc** [comment]
24/OCT/23
- will not need to do this given the success of the experiments with TAP services and multiple TAP services (ie #442)
