### ISSUE TITLE
Create fork of Vollt source code & apply our changes

### ISSUE THREAD

**Issue by stvoutsin** [wfau/ScienceArchives#417]
Fork the following:
https://github.com/gmantele/vollt/tree/master/src/tap

Apply changes needed to get it working with our SQL Server databases

**Comment by tms-epcc** [comment]
01/AUG/23
- @stvoutsin forked in own repo and applied changes there
- once happy will create fork under WFAU when production ready

**Comment by tms-epcc** [comment]
31/AUG/23
- some changes had to be made to the source code 
  - 5 files changed 
  - will need to decide if these need to go back to the Vollt repo 
  - Not expected to be much of a a risk that if Vollt code is altered, it will affect the WFAU version of it
  - making changes generic enough that they be pulled back to Vollt repo via PRs.  Acceptance will depend on the Vollt owners 
  - if do not get accepted, there are existing forks (eg Space Telescope), will just need to manage changes. Not expected to be daily or weekly changes 
- will create fork in WFAU production repo this week

**Comment by tms-epcc** [comment]
18/SEP/23
- this is done 
- see https://github.com/wfau/vollt
