### ISSUE TITLE
Document what needs to be changed to get Vollt TAP service working on Somerville

### ISSUE THREAD

**Issue by stvoutsin** [wfau/ScienceArchives#418]
Includes:
- Deploying Vollt on Somerville
- Accessing SQL Server databases on Somerville

For example:
We need an account on the new server (tapuser) that can access the read-only data databases & create databases (TAP_SCHEMA) on the same server

**Comment by tms-epcc** [comment]
31/AUG/23
- again waiting for DBs to move to Somerville but will start wiki page in the meantime

**Comment by tms-epcc** [comment]
- process will be the same whether on Somervile or awnywhere ealse
- all that needs changed is the DB connection
- @stvoutsin will add this to the deploy documentaton
