### ISSUE TITLE
Dockerize the Vollt TAP service for WFAU

### ISSUE THREAD

**Issue by stvoutsin** [wfau/ScienceArchives#419]
Create Docker container / docker-compose file to allow deploying a Vollt TAP service as a container

**Comment by tms-epcc** [comment]
01/AUG/23
 - for most part complete
 - run on a VM but unable to access DB servers
 - need to speak to @MikeeRead about what DB traffic is allowed

**Comment by tms-epcc** [comment]
31/AUG/23
- since DBs will not be available until end of year, progress is blocked 
- want to document before closing the issue

**Comment by tms-epcc** [comment]
@astrodb reported
- prototpye being built on Somerville Ubunti
- SQL Server now needs a paid for licence with latest version
- hacked machine to run older version of SQL server for the moment
- this will need consideration for longer term - either buy or run old version on Ubuntu 
- @astrodb  will investigate how much  license costs and contact SoPA

**Comment by tms-epcc** [comment]
15/SEP/23
- prototype service uses SQL server 
- all works ok
