### ISSUE TITLE
Deploy prototype of Vollt WFAU TAP service on Somerville

### ISSUE THREAD

**Issue by stvoutsin** [wfau/ScienceArchives#420]
Deploy prototype on a publicly accessible VM with basic functionality enabled.
May include bugs, purpose is to setup a first "hello world" version of it on a Somerville VM.

**Comment by tms-epcc** [comment]
01/AUG/23
- needs DBS to be moved to Somerville.
- that migration is not expected until later in the year

**Comment by tms-epcc** [comment]
31/AUG/23
- in advance of DB migrations, get a mock-up of the prototype TAP service running on Somerville in order to check all is working
- @stvoutsin will ask @astrodb since need a DB account on the Somerville DB being read/write to

**Comment by tms-epcc** [comment]
15/SEP/23
- @stvoutsin created prototype service on Somerville with connection VST ATLAS DR5
- will demo at next meeting when Somerville back on line

**Comment by tms-epcc** [comment]
04/OCT/23
- demo of TAP service 
- connected to Atlas DR5 on Somerville
