### ISSUE TITLE
Create tableset XML file with all database/tables included

### ISSUE THREAD

**Issue by stvoutsin** [wfau/ScienceArchives#421]
We may end up with one single TAP service for all databases/tables. To investigate if this is possible we need one single tableset metadata XML file with all databases/tables to be exposed included.

**Comment by tms-epcc** [comment]
01/AUG/23
- need to decide if one  big TAP service 
- needs further investigation since this would produce a very large metadata document which can cause issues for some  clients

**Comment by tms-epcc** [comment]
31/AUG/23
 - if separate TAP services then would have own container or VM but all cannot connect to the same DB server 
 - needs further discussion with @astrodb 
 - need to test if clients instead can access one large metadata document without issues arising.

**Comment by tms-epcc** [comment]
04/OCT/23
- first version ready
- not yet tested 
- need to point the TAP service back to ramses service since Somerville does not yet have all the DBs on it.
