### ISSUE TITLE
Run CU19

### ISSUE THREAD

**Issue by esutorius** [wfau/ScienceArchives#430]

**Comment by tms-epcc** [comment]
25/AUG/23
- @esutorius waiting for @wfastrononomer to fix some items before being able to progress this
- @wfastrononomer aware of the need in relation to other priorities

**Comment by tms-epcc** [comment]
08/SEP23
- this is now fixed and finished
- browser pages created so all is available 
- need to wait for @MikeeRead to send out to Maria and confirmed can be closed
