### ISSUE TITLE
run FinaliseCatalogueIngest (-03/23)

### ISSUE THREAD

**Issue by esutorius** [wfau/ScienceArchives#473]

**Comment by tms-epcc** [comment]
15/DEC/23
- @esutorius reported via email to @tms-epcc 

> Fully ingested the WFCAM data up to 2023/03. Also updated theobjectIDs and the QualityBits.

**Comment by tms-epcc** [comment]
30/JAN/24
- @esutorius confirmed at [26/JAN/24 SA meeting](https://www.wiki.ed.ac.uk/pages/viewpage.action?pageId=618208000) that this can be closed.
