### ISSUE TITLE
Update CU8 to avoid misclassification of stars to galaxies

### ISSUE THREAD

**Issue by tms-epcc** [wfau/ScienceArchives#488]
Deep mosaics processed with SExtractor may have misclassifications of stars to galaxies or vice versa that leads to too few objects in the calculation of zeropoints. One way to avoid this is to allow all objects from the deep catalogues to be matched against good stars from the intermediate. A better method in the longer term is to fix the classification problem.

Used to get 40-50000 frames deprecated due to misclassifications. Now ~1500. Will do a few more checks

**Comment by wfastrononomer** [comment]
Lower priority for now. Sort out the matched aperture work first.

**Comment by tms-epcc** [comment]
08/MAY/24
- looks to be mostly working when run with CU6
- but need to check the details

**Comment by tms-epcc** [comment]
11/JUL/24
- still to complete check to see if this can be closed
