### ISSUE TITLE
CU34 error in ingesting list-driven catalogues

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#508]
# 2024-03-20 14:15:33.62: Preparing CU run for Cu34 for 20091204_v1.5
# 2024-03-20 14:15:33.63: <ERROR> Programming Error: AttributeError: 'DataBuilder' object has no attribute '_detectionSubset'

Traceback (most recent call last):
  File "/pepy/njc/VDFS/ListDrivenClean/src/curation/wsatools/DbConnect/IngCuSession.py", line 1218, in run
    self._onRun()
  File "/pepy/njc/VDFS/ListDrivenClean/src/curation/invocations/cu0/DataBuilder.py", line 1122, in _onRun
    self.prepareCu34s(filePath)
  File "/pepy/njc/VDFS/ListDrivenClean/src/curation/invocations/cu0/DataBuilder.py", line 1317, in prepareCu34s
    detectionSubset=self._detectionSubset,

Fixed - but next error:

# 2024-03-20 16:16:35.30: <ERROR> str: [12951] ValueError('Map /disk62/sys/test/
products/map/20240319_v5/v20220519_00176_st_map160_2_1.fits should have known pr
ogrammeID: probably a missing PROGID key',)

Traceback (most recent call last):
  File "/pepy/njc/VDFS/ListDrivenClean/src/curation/invocations/cu4/cu4.py", lin
e 370, in _onRun
    catsForProg = self.getProgIDs()
  File "/pepy/njc/VDFS/ListDrivenClean/src/curation/invocations/cu4/cu4.py", lin
e 746, in getProgIDs
    self.getProgramIDs(self._shortListFile.name)
  File "/pepy/njc/VDFS/ListDrivenClean/src/curation/wsatools/DbConnect/IngCuSess
ion.py", line 1002, in getProgramIDs
    "probably a missing PROGID key" % fileName)

Fixed: 
# 2024-03-21 12:38:11.39: exnumeric -tables /pepy/tmp/njc_59949.0041/schema_160.
dat -files /pepy/tmp/njc_59949.0041/filelist_160_0.dat -cuEvent 72921 -csvpath /
pepy/samba/share/  -sqlpath /pepy/njc/VDFS/ListDrivenClean/sql -csvprefix cu34id
72921_pepy-1_testVSAnjcUV2_casu -illumname /pepy/tmp/njc_59949.0041/illumTables.
dat -outtables  -newobjid 0 -archive VSA -extractor CASU
# 2024-03-21 12:38:11.41: # ----------------------------------------------------
----
# 2024-03-21 12:38:11.41: # One of my exceptions was caught!
# 2024-03-21 12:38:11.41: # OptionException: Option 'extractor' unspecified
# 2024-03-21 12:38:11.41: # ----------------------------------------------------
----
# 2024-03-21 12:38:11.41: <ERROR> str: [72921] Error('exnumeric failed',)

-----------------

17/5/2024: Test on small standalone file worked. Will do more tests on larger ones and try to work through issues.

**Comment by tms-epcc** [comment]
10/APR/24
- not sure exactly where this is failing so needs further investigation

**Comment by tms-epcc** [comment]
05/JUN/24
- this is now working and can be closed
