### ISSUE TITLE
Check if there are any other team data.

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#523]
Check with VMC team for other products.

Asked Maria-Rosa - specifically asked her about Cepheids and Eclipsing Binaries. She said she will check

**Comment by tms-epcc** [comment]
05/JUN/24
- contacted Maria-Rosa, recvd no reply but will ask again just in case

**Comment by tms-epcc** [comment]
11/JUL/24
- done and tickets added
