### ISSUE TITLE
Make changes to Automator/cu29 to make sure there are neighbour tables from ultravistaMultiBandCatalogue to external surveys

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#524]
In my test database testVSAnjcUVDR6, there is a neighbour table ultravistaSourceXMultiBandCatalogue, and ones from ultravistaSource to external survey, but none from the multiband to other surveys.

**Comment by tms-epcc** [comment]
08/MAY/24
- working on earlier parts of CU29 so will look at this soon

**Comment by tms-epcc** [comment]
05/JUN/24
- tested on VMC and seems to be working
- need to check for UltraVISTA

**Comment by tms-epcc** [comment]
11/JUL/24
- will run one more check

**Comment by tms-epcc** [comment]
14/AUG/24
- this is done
