### ISSUE TITLE
Deprecate filterID=9,10 frames in VVVX.

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#533]
There are about 50 frames with filterID=9,10. What are they? Why are they in VVVX. At any rate they should not be used.

**Comment by tms-epcc** [comment]
08/MAY/24
@wfastrononomer reported
- worried about where these extra filters come from
- need to check their origin with @esutorius and whether they need to be deprecated

**Comment by tms-epcc** [comment]
05/JUN/24
- still to do above check

**Comment by tms-epcc** [comment]
14/AUG/24
- this is done
