### ISSUE TITLE
Add EPOCH to PM catalogues.

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#537]
These are not in the data structure. 
They are sent separately. Add new column.

Horrible format.

**Comment by tms-epcc** [comment]
05/JUN/24
- need information for new catalogue

**Comment by tms-epcc** [comment]
11/JUL/24
- have some data 
- now need to add method

**Comment by wfastrononomer** [comment]
Need a new function in cu29.Converter for this.

**Comment by wfastrononomer** [comment]
Added code for auxiliary data and function for epochAux data. Is working.
