### ISSUE TITLE
Found bug in RRLyrae catalogues - waiting for feedback from team.

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#539]
Some JMean values in stats table are very different to the mean(J) from light-curve table. e.g. one had Jmean = 18.25, and 4 light-curve measurements all of which ~13.1 mag.

**Comment by tms-epcc** [comment]
05/JUN/24
- in progress

**Comment by tms-epcc** [comment]
11/JUL/25
- this can be closed
