### ISSUE TITLE
Look up literature values for WFCAM to VISTA calibration.

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#548]
Use CASU plone (and Hodgkin, Fernandez-Gonzalez papers), and possibly other papers.

**Comment by wfastrononomer** [comment]
Section 6 of Gonzalez Fernandez papers.

I have to be careful when no or limited colour info.
Perhaps get colours as a function of mag,l,b (other colours) and take median if poor photometry, or if no detection, use mag limit information.

**Comment by tms-epcc** [comment]
14/AUG/24
- once in code will close this ticket

**Comment by tms-epcc** [comment]
16/OCT/24
- now in code ie reading in the file with these
- can now close
