### ISSUE TITLE
Modify code to use new columns

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#573]
Modified band columns: zAperMag3 --> zAllAperMag3, zTelAperMag3. Need to modify code, or add tags to schema to use these correctly.  
Also other new columns - homoJKsources, isObs/Meas

**Comment by wfastrononomer** [comment]
Created new test database with new schemas (still doing updates) and testing with small 1 sq. deg area
Updated so mag columns with Tel in work - copy from releases. Colour columns mostly work too.

**Comment by wfastrononomer** [comment]
Seem to be working. Colour mag work. isVista columns working. mID, eNum working. Need more definitive checks though.

Obs columns not working. Failing when mfID>0 and seqNum>0. May also fail elsewhere.

**Comment by tms-epcc** [comment]
14/AUG/24
- willclose this and create two new issues 
1. Homogeneous JK sources
2. All SKy calibration columns
