### ISSUE TITLE
xMeas -> should that be xObs?

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#587]
z/y/j/h/kMeas - should that be zyjhkObs? -> should tell you if there are pixels for that source in that frameset. --/Q tag to use seqNum/mfID

**Comment by wfastrononomer** [comment]
More complicated that mfID,seqNum.
If mfID<0 --> Obs = 0
elif seqNum > 0 -- > Obs = 1
else: use WCS to check if good?

**Comment by tms-epcc** [comment]
07/AUG/24
- this needs to explained in the paper
