### ISSUE TITLE
Is PawprintValuesAverager running?

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#588]
Now that matched aperture processing is running faster - check PawprintAveraging. This doesn't seem to have happened. Is this a bug in the pipeline, or in the PawprintAverager code.
Check logs etc.

**Comment by wfastrononomer** [comment]
No ArchiveCurationHistory rows with cuID=36

**Comment by wfastrononomer** [comment]
usePawprints - but update this - if entries in RequiredMapAverages and paw prints.

Also add entries to RequiredMapAverages.
See ramses19.ULTRAVISTADR4

select * from RequiredMapAverages
-------------------------------------------------------------------------------------------------------------------------------------------------
| | programmeID | mapID      | setupID    | description           | useDeeps | useHighProd | timeScale                | nEpochs    | overLaps | |
-------------------------------------------------------------------------------------------------------------------------------------------------
|>| 160         | 2          | 0          | Average over 3 months | 0        | NONE        | 91                       | -99999999  | 0        |<|
|>| 160         | 2          | 1          | Average over 6 months | 0        | NONE        | 183                      | -99999999  | 0        |<|
|>| 160         | 2          | 2          | Average over 1 year   | 0        | NONE        | 365                      | -99999999  | 0        |<|
-------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by tms-epcc** [comment]
14/AUG/24
- this is running now need some further tests
