### ISSUE TITLE
Write Calibration code

### ISSUE THREAD

**Issue by tms-epcc** [wfau/ScienceArchives#602]
@wfastrononomer requested this ticket be created

**Comment by wfastrononomer** [comment]
Initial code started.

**Comment by tms-epcc** [comment]
16/OCT/24
- need to break this down into more tickets

**Comment by wfastrononomer** [comment]
Basic code seems to work: processes 2 million rows in ~3 minutes, of which 500,000 are UKIRT (need calibration) and 1.5million are VISTA - requires copying over data.

Add more checks, improve logging, in later issues
