### ISSUE TITLE
Why is tempColour always the same number of rows irrespective of which frameSet?

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#630]
# 2024-10-18 12:21:37.71: Transferring ingest file to teti...
# 2024-10-18 12:21:37.71: Ingesting into tempColour...
# 2024-10-18 12:21:37.73: done! Rows affected = 1015
# 2024-10-18 12:21:37.73: Created temporary table tempColour with 1015 rows
# 2024-10-18 12:21:37.98: Updated 0 calibrated magnitudes and colours in framese
t 433791697767
# 2024-10-18 12:21:38.06: Number of objects with default colours = 444 out of 75
2
# 2024-10-18 12:21:38.07: Number of objects with default colours after updating
= 0
# 2024-10-18 12:21:38.07: Creating temporary table of colours tempColour...
# 2024-10-18 12:21:38.07: Created temporary ingest file, /disk62/sys/test/produc
ts/temp/20241018/tempColour.csv for temporary table
# 2024-10-18 12:21:38.07: Transferring ingest file to teti...
# 2024-10-18 12:21:38.07: Ingesting into tempColour...
# 2024-10-18 12:21:38.09: done! Rows affected = 1015
# 2024-10-18 12:21:38.09: Created temporary table tempColour with 1015 rows
# 2024-10-18 12:21:38.34: Updated 0 calibrated magnitudes and colours in framese
t 433791697768
# 2024-10-18 12:21:38.42: Number of objects with default colours = 0 out of 0
# 2024-10-18 12:21:38.42: Number of objec

**Comment by tms-epcc** [comment]
Fixed
