### ISSUE TITLE
Created tiles for Dante - need to rename files on disk and in archive.

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#638]
Dante asked to see the deep stacks for b336 as a radio transient had been detected there. I checked to see if products had been created or were in the process of being created, but they weren't so produced them. He also asked for a comparison field away from the bulge and suggested b211 and that also hadn't been produced.

cu13 completed. The stacks and tiles are /disk62/sys/test/products, so should probably be moved to a different location. There are links in ProductProcessing to these files, although these would be deleted after ingest.

The new ones are in:
/disk62/sys/test/products/stacks/20241022_v2/
/disk62/sys/test/products/stacks/20241027_v2/

/disk62/sys/test/products/tiles/20241022_v2/
/disk62/sys/test/products/tiles/20241025_v2/
/disk62/sys/test/products/tiles/20241027_v2/

**Comment by tms-epcc** [comment]
20/NOV/24
- discussed with @esutorius 
- @esutorius - is this done?

**Comment by esutorius** [comment]
yes, that was done.
